cmd_scripts/kconfig/qconf.o := g++ -Wp,-MD,scripts/kconfig/.qconf.o.d -O2  -DQT_SHARED -DQT_TABLET_SUPPORT -DQT_NO_DEBUG -DQT_THREAD_SUPPORT -D_REENTRANT -I/usr/include/qt3   -D LKC_DIRECT_LINK -c -o scripts/kconfig/qconf.o scripts/kconfig/qconf.cc

deps_scripts/kconfig/qconf.o := \
  scripts/kconfig/qconf.cc \
  /usr/include/qt3/qapplication.h \
  /usr/include/qt3/qdesktopwidget.h \
  /usr/include/qt3/qwidget.h \
  /usr/include/qt3/qwindowdefs.h \
  /usr/include/qt3/qobjectdefs.h \
  /usr/include/qt3/qglobal.h \
    $(wildcard include/config/local.h) \
    $(wildcard include/config/minimal.h) \
    $(wildcard include/config/small.h) \
    $(wildcard include/config/medium.h) \
    $(wildcard include/config/large.h) \
  /usr/include/qt3/qconfig.h \
  /usr/include/qt3/qmodules.h \
  /usr/include/qt3/qfeatures.h \
  /usr/include/qt3/qstring.h \
  /usr/include/qt3/qcstring.h \
  /usr/include/qt3/qmemarray.h \
  /usr/include/qt3/qgarray.h \
  /usr/include/qt3/qshared.h \
  /usr/include/qt3/qwinexport.h \
  /usr/include/string.h \
  /usr/include/features.h \
  /usr/include/x86_64-linux-gnu/bits/predefs.h \
  /usr/include/x86_64-linux-gnu/sys/cdefs.h \
  /usr/include/x86_64-linux-gnu/bits/wordsize.h \
  /usr/include/x86_64-linux-gnu/gnu/stubs.h \
  /usr/include/x86_64-linux-gnu/gnu/stubs-64.h \
  /usr/lib/gcc/x86_64-linux-gnu/4.6/include/stddef.h \
  /usr/include/xlocale.h \
  /usr/include/x86_64-linux-gnu/bits/string3.h \
  /usr/lib/gcc/x86_64-linux-gnu/4.6/include-fixed/limits.h \
  /usr/lib/gcc/x86_64-linux-gnu/4.6/include-fixed/syslimits.h \
  /usr/include/limits.h \
  /usr/include/x86_64-linux-gnu/bits/posix1_lim.h \
  /usr/include/x86_64-linux-gnu/bits/local_lim.h \
  /usr/include/linux/limits.h \
  /usr/include/x86_64-linux-gnu/bits/posix2_lim.h \
  /usr/include/x86_64-linux-gnu/bits/xopen_lim.h \
  /usr/include/x86_64-linux-gnu/bits/stdio_lim.h \
  /usr/include/c++/4.6/string \
  /usr/include/c++/4.6/x86_64-linux-gnu/./bits/c++config.h \
    $(wildcard include/config/h.h) \
  /usr/include/c++/4.6/x86_64-linux-gnu/./bits/os_defines.h \
  /usr/include/c++/4.6/x86_64-linux-gnu/./bits/cpu_defines.h \
  /usr/include/c++/4.6/bits/stringfwd.h \
  /usr/include/c++/4.6/bits/char_traits.h \
  /usr/include/c++/4.6/bits/stl_algobase.h \
  /usr/include/c++/4.6/bits/functexcept.h \
  /usr/include/c++/4.6/bits/exception_defines.h \
  /usr/include/c++/4.6/bits/cpp_type_traits.h \
  /usr/include/c++/4.6/ext/type_traits.h \
  /usr/include/c++/4.6/ext/numeric_traits.h \
  /usr/include/c++/4.6/bits/stl_pair.h \
  /usr/include/c++/4.6/bits/move.h \
  /usr/include/c++/4.6/bits/concept_check.h \
  /usr/include/c++/4.6/bits/stl_iterator_base_types.h \
  /usr/include/c++/4.6/bits/stl_iterator_base_funcs.h \
  /usr/include/c++/4.6/bits/stl_iterator.h \
  /usr/include/c++/4.6/debug/debug.h \
  /usr/include/c++/4.6/bits/postypes.h \
  /usr/include/c++/4.6/cwchar \
  /usr/include/wchar.h \
  /usr/include/stdio.h \
  /usr/lib/gcc/x86_64-linux-gnu/4.6/include/stdarg.h \
  /usr/include/x86_64-linux-gnu/bits/wchar.h \
  /usr/include/x86_64-linux-gnu/bits/wchar2.h \
  /usr/include/c++/4.6/bits/allocator.h \
  /usr/include/c++/4.6/x86_64-linux-gnu/./bits/c++allocator.h \
  /usr/include/c++/4.6/ext/new_allocator.h \
  /usr/include/c++/4.6/new \
  /usr/include/c++/4.6/exception \
  /usr/include/c++/4.6/bits/localefwd.h \
  /usr/include/c++/4.6/x86_64-linux-gnu/./bits/c++locale.h \
  /usr/include/c++/4.6/clocale \
  /usr/include/locale.h \
  /usr/include/x86_64-linux-gnu/bits/locale.h \
  /usr/include/c++/4.6/iosfwd \
  /usr/include/c++/4.6/cctype \
  /usr/include/ctype.h \
  /usr/include/x86_64-linux-gnu/bits/types.h \
  /usr/include/x86_64-linux-gnu/bits/typesizes.h \
  /usr/include/endian.h \
  /usr/include/x86_64-linux-gnu/bits/endian.h \
  /usr/include/x86_64-linux-gnu/bits/byteswap.h \
  /usr/include/c++/4.6/bits/ostream_insert.h \
  /usr/include/c++/4.6/bits/cxxabi_forced.h \
  /usr/include/c++/4.6/bits/stl_function.h \
  /usr/include/c++/4.6/backward/binders.h \
  /usr/include/c++/4.6/bits/range_access.h \
  /usr/include/c++/4.6/bits/basic_string.h \
  /usr/include/c++/4.6/ext/atomicity.h \
  /usr/include/c++/4.6/x86_64-linux-gnu/./bits/gthr.h \
  /usr/include/c++/4.6/x86_64-linux-gnu/./bits/gthr-default.h \
  /usr/include/pthread.h \
  /usr/include/sched.h \
  /usr/include/time.h \
  /usr/include/x86_64-linux-gnu/bits/sched.h \
  /usr/include/x86_64-linux-gnu/bits/time.h \
  /usr/include/x86_64-linux-gnu/bits/timex.h \
  /usr/include/x86_64-linux-gnu/bits/pthreadtypes.h \
  /usr/include/x86_64-linux-gnu/bits/setjmp.h \
  /usr/include/unistd.h \
  /usr/include/x86_64-linux-gnu/bits/posix_opt.h \
  /usr/include/x86_64-linux-gnu/bits/environments.h \
  /usr/include/x86_64-linux-gnu/bits/confname.h \
  /usr/include/getopt.h \
  /usr/include/x86_64-linux-gnu/bits/unistd.h \
  /usr/include/c++/4.6/x86_64-linux-gnu/./bits/atomic_word.h \
  /usr/include/c++/4.6/initializer_list \
  /usr/include/c++/4.6/bits/basic_string.tcc \
  /usr/include/qt3/qnamespace.h \
  /usr/include/qt3/qobject.h \
  /usr/include/qt3/qevent.h \
  /usr/include/qt3/qregion.h \
  /usr/include/qt3/qrect.h \
  /usr/include/qt3/qsize.h \
  /usr/include/qt3/qpoint.h \
  /usr/include/qt3/qmime.h \
  /usr/include/qt3/qmap.h \
  /usr/include/qt3/qdatastream.h \
  /usr/include/qt3/qiodevice.h \
  /usr/include/qt3/qpair.h \
  /usr/include/qt3/qvaluelist.h \
  /usr/include/qt3/qtl.h \
  /usr/include/qt3/qtextstream.h \
  /usr/include/libio.h \
  /usr/include/_G_config.h \
  /usr/include/x86_64-linux-gnu/bits/sys_errlist.h \
  /usr/include/x86_64-linux-gnu/bits/stdio.h \
  /usr/include/x86_64-linux-gnu/bits/stdio2.h \
  /usr/include/c++/4.6/iterator \
  /usr/include/c++/4.6/ostream \
  /usr/include/c++/4.6/ios \
  /usr/include/c++/4.6/bits/ios_base.h \
  /usr/include/c++/4.6/bits/locale_classes.h \
  /usr/include/c++/4.6/bits/locale_classes.tcc \
  /usr/include/c++/4.6/streambuf \
  /usr/include/c++/4.6/bits/streambuf.tcc \
  /usr/include/c++/4.6/bits/basic_ios.h \
  /usr/include/c++/4.6/bits/locale_facets.h \
  /usr/include/c++/4.6/cwctype \
  /usr/include/wctype.h \
  /usr/include/c++/4.6/x86_64-linux-gnu/./bits/ctype_base.h \
  /usr/include/c++/4.6/bits/streambuf_iterator.h \
  /usr/include/c++/4.6/x86_64-linux-gnu/./bits/ctype_inline.h \
  /usr/include/c++/4.6/bits/locale_facets.tcc \
  /usr/include/c++/4.6/bits/basic_ios.tcc \
  /usr/include/c++/4.6/bits/ostream.tcc \
  /usr/include/c++/4.6/istream \
  /usr/include/c++/4.6/bits/istream.tcc \
  /usr/include/c++/4.6/bits/stream_iterator.h \
  /usr/include/c++/4.6/list \
  /usr/include/c++/4.6/bits/stl_list.h \
  /usr/include/c++/4.6/bits/list.tcc \
  /usr/include/c++/4.6/cstddef \
  /usr/include/c++/4.6/map \
  /usr/include/c++/4.6/bits/stl_tree.h \
  /usr/include/c++/4.6/bits/stl_map.h \
  /usr/include/c++/4.6/bits/stl_multimap.h \
  /usr/include/qt3/qpaintdevice.h \
  /usr/include/qt3/qpalette.h \
  /usr/include/qt3/qcolor.h \
  /usr/include/qt3/qstringlist.h \
  /usr/include/qt3/qstrlist.h \
  /usr/include/qt3/qptrlist.h \
  /usr/include/qt3/qglist.h \
  /usr/include/qt3/qptrcollection.h \
  /usr/include/qt3/qbrush.h \
  /usr/include/qt3/qfont.h \
  /usr/include/qt3/qfontmetrics.h \
  /usr/include/qt3/qfontinfo.h \
  /usr/include/qt3/qsizepolicy.h \
  /usr/include/qt3/qasciidict.h \
  /usr/include/qt3/qgdict.h \
  /usr/include/qt3/qtranslator.h \
  /usr/include/qt3/qmainwindow.h \
  /usr/include/qt3/qtoolbar.h \
  /usr/include/qt3/qdockwindow.h \
  /usr/include/qt3/qframe.h \
  /usr/include/qt3/qdesktopwidget.h \
  /usr/include/qt3/qtoolbar.h \
  /usr/include/qt3/qlayout.h \
  /usr/include/qt3/qvbox.h \
  /usr/include/qt3/qhbox.h \
  /usr/include/qt3/qsplitter.h \
  /usr/include/qt3/qlistview.h \
  /usr/include/qt3/qscrollview.h \
  /usr/include/qt3/qscrollbar.h \
  /usr/include/qt3/qrangecontrol.h \
  /usr/include/qt3/qtextbrowser.h \
  /usr/include/qt3/qpixmap.h \
  /usr/include/qt3/qtextedit.h \
  /usr/include/qt3/qstylesheet.h \
  /usr/include/qt3/qptrvector.h \
  /usr/include/qt3/qgvector.h \
  /usr/include/qt3/qdict.h \
  /usr/include/qt3/qlineedit.h \
  /usr/include/qt3/qlabel.h \
  /usr/include/qt3/qpushbutton.h \
  /usr/include/qt3/qbutton.h \
  /usr/include/qt3/qkeysequence.h \
  /usr/include/qt3/qiconset.h \
  /usr/include/qt3/qmenubar.h \
  /usr/include/qt3/qpopupmenu.h \
  /usr/include/qt3/qmenudata.h \
  /usr/include/qt3/qsignal.h \
  /usr/include/qt3/qvariant.h \
  /usr/include/qt3/qmessagebox.h \
  /usr/include/qt3/qdialog.h \
  /usr/include/qt3/qaction.h \
  /usr/include/qt3/qheader.h \
  /usr/include/qt3/qfiledialog.h \
  /usr/include/qt3/qdir.h \
  /usr/include/qt3/qfileinfo.h \
  /usr/include/qt3/qfile.h \
  /usr/include/qt3/qdatetime.h \
  /usr/include/qt3/qurloperator.h \
  /usr/include/qt3/qurl.h \
  /usr/include/qt3/qnetworkprotocol.h \
  /usr/include/qt3/qurlinfo.h \
  /usr/include/qt3/qdragobject.h \
  /usr/include/qt3/qimage.h \
  /usr/include/qt3/qregexp.h \
  /usr/include/stdlib.h \
  /usr/include/x86_64-linux-gnu/bits/waitflags.h \
  /usr/include/x86_64-linux-gnu/bits/waitstatus.h \
  /usr/include/x86_64-linux-gnu/sys/types.h \
  /usr/include/x86_64-linux-gnu/sys/select.h \
  /usr/include/x86_64-linux-gnu/bits/select.h \
  /usr/include/x86_64-linux-gnu/bits/sigset.h \
  /usr/include/x86_64-linux-gnu/bits/select2.h \
  /usr/include/x86_64-linux-gnu/sys/sysmacros.h \
  /usr/include/alloca.h \
  /usr/include/x86_64-linux-gnu/bits/stdlib.h \
  scripts/kconfig/lkc.h \
    $(wildcard include/config/list.h) \
  scripts/kconfig/expr.h \
  /usr/include/libintl.h \
  scripts/kconfig/lkc_proto.h \
  scripts/kconfig/qconf.h \
  /usr/include/qt3/qsettings.h \
  scripts/kconfig/qconf.moc \
  /usr/include/qt3/qmetaobject.h \
  /usr/include/qt3/qconnection.h \
  /usr/include/qt3/private/qucomextra_p.h \
  /usr/include/qt3/private/qucom_p.h \
  /usr/include/qt3/qstring.h \
  /usr/include/qt3/quuid.h \
  /usr/include/qt3/qobjectdefs.h \
  /usr/include/qt3/qsignalslotimp.h \
  scripts/kconfig/images.c \

scripts/kconfig/qconf.o: $(deps_scripts/kconfig/qconf.o)

$(deps_scripts/kconfig/qconf.o):
